#ifndef MACROS_H
#define MACROS_H

#define MAX_NUMBER_OF_BLOCKS 1024
#define MAX_BLOCK_SIZE 512
#define MAX_INPUT_LENGTH 100
#define MAX_FILENODE_NAME_LENGTH 50
#define MAX_COMMAND_LENGTH 200
#define MAX_CONTENT_LENGTH 100

#endif